Modules/Seller/Routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\Setup\Http\Controllers\CountryController;

Route::middleware(['auth','seller'])->prefix('seller')->as('seller.')->group(function() {
    //support ticket
    Route::get('/support-ticket','SupportTicketController@index')->name('support-ticket.index');
    Route::get('/support-ticket/get-data','SupportTicketController@getData')->name('support-ticket.get-data');
    Route::get('/support-ticket/create','SupportTicketController@create')->name('support-ticket.create');
    Route::get('/support-ticket/{id}/edit','SupportTicketController@edit')->name('support-ticket.edit');
    Route::post('/support-ticket','SupportTicketController@store')->name('support-ticket.store')->middleware('prohibited_demo_mode');
    Route::post('/support-ticket/update/{id}','SupportTicketController@update')->name('support-ticket.update')->middleware('prohibited_demo_mode');
    Route::get('/support-ticket/{id}/show','SupportTicketController@show')->name('support-ticket.show');
    Route::post('/support-ticket/message','SupportTicketController@message')->name('ticket.message')->middleware('prohibited_demo_mode');
    Route::get('/support-ticket/search','SupportTicketController@search')->name('ticket.search');
    //product reviews
    Route::get('/product-reviews','ProductReviewsController@index')->name('product-reviews.index');
    Route::get('/product-reviews/get-data','ProductReviewsController@getData')->name('product-reviews.get-data')->middleware(['permission']);
    Route::get('/product-reviews/reply','ProductReviewsController@reply')->name('product-reviews.reply')->middleware(['permission']);
    Route::post('/product-reviews/reply','ProductReviewsController@replyStore')->name('product-reviews.reply.store')->middleware('prohibited_demo_mode');
    //seller reviews
    Route::get('/my-reviews','SellerReviewsController@index')->name('my-reviews.index');
    Route::get('/my-reviews/get-data','SellerReviewsController@getData')->name('my-reviews.get-data');
    //reports
    Route::get('/reports','ReportsController@index')->name('reports.index');
    //products
    Route::get('/product','ProductController@index')->name('product.index');
    Route::get('/product/get-data','ProductController@getData')->name('product.get-data');
    Route::post('/product-stock-status','ProductController@update_stock_manage_status')->name('product.update_stock_manage_status')->middleware('prohibited_demo_mode');
    Route::get('/product/{id}','ProductController@getProduct')->name('product.getByID');
    Route::post('/product-store','ProductController@store')->name('product.store')->middleware('prohibited_demo_mode');
    Route::post('/product/show','ProductController@show')->name('product.show');
    Route::post('/admin-product/show','ProductController@admin_product_show')->name('admin_product.show');
    Route::post('/sku-status', 'ProductController@updateSkuStatusByID')->name('product.sku.status')->middleware(['prohibited_demo_mode']);
    Route::post('/product/delete','ProductController@destroy')->name('product.delete')->middleware('prohibited_demo_mode');
    Route::get('/product/edit/{id}','ProductController@edit')->name('product.edit');
    Route::post('/product/update/{id}','ProductController@update')->name('product.update')->middleware('prohibited_demo_mode');
    Route::post('/product/update-status','ProductController@updateStatus')->name('product.update-status')->middleware('prohibited_demo_mode');
    Route::post('/product/variant','ProductController@variant')->name('product.variant');
    Route::post('/product/variant/edit','ProductController@variantEdit')->name('product.variant-edit');
    Route::post('/product/variant/delete','ProductController@variantDelete')->name('product.variant.delete')->middleware('prohibited_demo_mode');
    //my product
    Route::get('/products/create','ProductController@create')->name('product.create')->middleware(['permission']);
    Route::get('/product/{id}/edit','ProductController@myProductEdit')->name('my-product.edit');
    Route::get('/product/{id}/clone','ProductController@myProductClone')->name('my-product.clone');
    Route::get('/products/change-state','ProductController@changeState')->name('product.change-state');
    Route::resource('/supplier', 'SupplierController')->except('destroy');
    Route::post('/supplier/delete','SupplierController@destroy')->name('supplier.delete');
    Route::post('/supplier/status-update','SupplierController@statusChange')->name('supplier.status-update');
});
Route::prefix('seller')->as('seller.')->group(function() {
    Route::get('/profile/get-state',[CountryController::class, 'get_states'])->name('profile.get-state');
    Route::get('/profile/get-city',[CountryController::class, 'get_cities'])->name('profile.get-city');
    Route::post('/get-seller-product-ku-wise-price', 'ProductController@get_seller_product_sku_wise_price')->name('get_seller_product_sku_wise_price');
    Route::post('/get-seller-product-variant-wise-price', 'ProductController@get_seller_product_variant_wise_price')->name('get_seller_product_variant_wise_price');
});
Route::middleware(['auth','admin'])->prefix('admin')->group(function() {
    if(isModuleActive('MultiVendor')){
    //inhouse product
        Route::get('/inhouse/product','ProductController@index')->name('admin.my-product.index')->middleware(['permission']);
        Route::get('/inhouse/products/create','ProductController@create')->name('admin.my-product.create')->middleware(['permission']);
        Route::get('/inhouse/product/edit/{id}','ProductController@edit')->name('admin.my-product.edit')->middleware(['permission']);
    }
});

Modules/Seller/Entities/Supplier.php
<?php

namespace Modules\Seller\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Modules\Setup\Entities\Country;

class Supplier extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
    
    protected static function newFactory()
    {
        return \Modules\Seller\Database\factories\SupplierFactory::new();
    }

    public function country(){
        return Country::where('code',$this->country)->firstOrFail();
    }
}

Modules/Seller/Http/Controllers/SupplierController.php
<?php

namespace Modules\Seller\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Seller\Services\SupplierService;
use Modules\Setup\Entities\Country;
use Brian2694\Toastr\Facades\Toastr;
use Modules\Seller\Http\Requests\SupplierRequest;

class SupplierController extends Controller
{
    protected $supplierService;
    public function __construct(SupplierService $supplierService)
    {
        $this->middleware('maintenance_mode');
        $this->supplierService = $supplierService;
    }

    public function index()
    {
        $suppliers = $this->supplierService->getAll();
        return view('seller::supplier.index',compact('suppliers'));
    }


    public function create()
    {
        $countries = Country::all();
        return view('seller::supplier.components.create',compact('countries'));
    }


    public function store(SupplierRequest $request)
    {

        $this->supplierService->store($request->except('_token'));

        \LogActivity::successLog('supplier added');
        Toastr::success(__('common.created_successfully'),__('common.success'));
        return redirect()->route('seller.supplier.index');
    }


    public function show($id)
    {
        $supplier = $this->supplierService->editByID($id);
        return view('seller::supplier.components.view',compact('supplier'));
    }


    public function edit($id)
    {
        $supplier = $this->supplierService->editByID($id);
        $countries = Country::all();
        return view('seller::supplier.components.edit',compact('supplier','countries'));
    }


    public function update(SupplierRequest $request, $id)
    {

        $this->supplierService->update($request->except('_token'),$id);

        \LogActivity::successLog('supplier updated');
        Toastr::success(__('common.updated_successfully'),__('common.success'));
        return redirect()->route('seller.supplier.index');
    }


    public function destroy(Request $request)
    {
        $this->supplierService->deleteByID($request->id);
        \LogActivity::successLog('Supplier deleted.');
        return $this->loadTableData();
    }

    public function statusChange(Request $request){

        $this->supplierService->statusChange($request->except('_token'));
        \LogActivity::successLog('supplier status changed');
        return $this->loadTableData();
    }

    private function loadTableData()
    {

        try {
            $suppliers = $this->supplierService->getAll();

            return response()->json([
                'SupplierList' =>  (string)view('seller::supplier.components.list', compact('suppliers')),
            ]);
        } catch (\Exception $e) {
            \LogActivity::errorLog($e->getMessage());
            Toastr::error(__('common.operation_failed'));
            return back();
        }
    }
}

Modules/Seller/Resources/views/supplier/index.blade.php
@extends('backEnd.master')

@section('mainContent')

    <section class="admin-visitor-area up_st_admin_visitor">


        @include('backEnd.partials._deleteModalForAjax',['item_name' => __('seller.supplier'),'form_id' =>
        'supplier_delete_form','modal_id' => 'supplier_delete_modal'])

        <div class="container-fluid p-0">
            <div class="row justify-content-center">

                <div class="col-12">
                    <div class="box_header common_table_header">
                        <div class="main-title d-md-flex">
                            <h3 class="mb-0 mr-30 mb_xs_15px mb_sm_20px">{{ __('seller.supplier_list') }}</h3>
                            
                                <ul class="d-flex">
                                    <li><a class="primary-btn radius_30px mr-10 fix-gr-bg"
                                            href="{{ route('seller.supplier.create') }}"><i
                                                class="ti-plus"></i>{{ __('common.add_new') }}
                                            {{ __('seller.supplier') }}</a></li>
                                </ul>
                            

                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="QA_section QA_section_heading_custom check_box_table">
                        <div class="QA_table">
                            <div class="" id="item_table">
                                @include('seller::supplier.components.list')

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

@endsection

@push('scripts')

    <script>
        $(document).ready(function() {
            $(document).on('submit', '#supplier_delete_form', function(event) {
                event.preventDefault();
                var formData = new FormData();
                formData.append('_token', "{{ csrf_token() }}");
                formData.append('id', $('#delete_item_id').val());
                let id = $('#delete_item_id').val();
                $.ajax({
                    url: "{{ route('seller.supplier.delete') }}",
                    type: "POST",
                    cache: false,
                    contentType: false,
                    processData: false,
                    data: formData,
                    success: function(response) {
                        resetAfterChange(response.SupplierList);
                        toastr.success("{{__('common.deleted_successfully')}}","{{__('common.success')}}")
                        $('#supplier_delete_modal').modal('hide');
                    },
                    error: function(response) {
                        toastr.error("{{__('common.error_message')}}","{{__('common.error')}}");
                    }
                });
            });
        });

        function update_active_status(el){
            if(el.checked){
                var status = 1;
            }
            else{
                var status = 0;
            }

            var formData = new FormData();
            formData.append('_token', "{{ csrf_token() }}");
            formData.append('id', el.value);
            formData.append('status', status);

            $.ajax({
                url: "{{ route('seller.supplier.status-update') }}",
                type: "POST",
                cache: false,
                contentType: false,
                processData: false,
                data: formData,
                success: function(response) {
                    resetAfterChange(response.SupplierList);
                    toastr.success("{{__('common.updated_successfully')}}","{{__('common.success')}}")
                },
                error: function(response) {
                    toastr.error("{{__('common.error_message')}}","{{__('common.error')}}");
                }
            });
        }

        function delete_modal(id) {
            $('#delete_item_id').val(id);
            $('#supplier_delete_modal').modal('show');
        }
        function resetAfterChange(supplierList) {
            $('#item_table').empty();
            $('#item_table').html(supplierList);

            CRMTableThreeReactive();
        }

    </script>

@endpush