Modules/FrontendCMS/Routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::middleware(['admin','auth'])->prefix('frontendcms')->as('frontendcms.')->group(function() {
    Route::get('/', 'FrontendCMSController@index');
    //feature
    Route::resource('features', 'FeatureController');
    Route::post('/features/store','FeatureController@store')->name('features.store')->middleware('prohibited_demo_mode');
    Route::get('/features/edit/{id}','FeatureController@edit')->name('features.edit');
    Route::post('/features/update/','FeatureController@update')->name('features.update')->middleware('prohibited_demo_mode');
    Route::post('/features/delete','FeatureController@delete')->name('features.delete')->middleware('prohibited_demo_mode');
    //subscribe content
    Route::get('/subscribe-content', 'SubcribeContentController@index')->name('subscribe-content.index');
    Route::post('/subscribe-content/update', 'SubcribeContentController@update')->name('subscribe-content.update')->middleware('prohibited_demo_mode');
    //popup content
    Route::get('/popup-content', 'SubcribeContentController@popup_index')->name('popup-content.index');
    Route::post('/popup-content/update', 'SubcribeContentController@popup_update')->name('popup-content.update')->middleware('prohibited_demo_mode');
    // promotion bar
    Route::get('/promotion-bar','PromotionbarController@index')->name('promotionbar.index');
    Route::post('/promotion-bar/update', 'PromotionbarController@update')->name('promotionbar.update')->middleware('prohibited_demo_mode');
    Route::get('/promotion-bar/remove-image','PromotionbarController@removeImage')->name('promotionbar.removeImage');
    // ads bar
    Route::get('/ads-bar','PromotionbarController@ads_index')->name('ads_bar.index');
    Route::post('/ads-bar/update', 'PromotionbarController@ads_update')->name('ads_bar.update')->middleware('prohibited_demo_mode');
    // random ads
    //about us
    Route::get('/about-us', 'AboutUsController@index')->name('about-us.index');
    Route::post('/about-us/update/{id}', 'AboutUsController@update')->name('about-us.update')->middleware('prohibited_demo_mode');
    //return & exchange
    Route::get('/return-exchange', 'ReturnExchangeController@index')->name('return-exchange.index');
    Route::post('/return-exchange/update', 'ReturnExchangeController@update')->name('return-exchange.update')->middleware('prohibited_demo_mode');
    //contact content
    Route::get('/contact-content', 'ContactContentController@index')->name('contact-content.index');
    Route::post('/contact-content/update', 'ContactContentController@update')->name('contact-content.update')->middleware('prohibited_demo_mode');
    //inquery
    Route::get('/query/create', 'ContactContentController@queryCreate')->name('query.create');
    Route::post('/query/store', 'ContactContentController@queryStore')->name('query.store')->middleware('prohibited_demo_mode');
    Route::post('/query/update','ContactContentController@queryUpdate')->name('query.update')->middleware('prohibited_demo_mode');
    Route::post('/query/delete','ContactContentController@destroy')->name('query.delete')->middleware('prohibited_demo_mode');
    Route::post('/query/status-update','ContactContentController@status')->name('query.status')->middleware('prohibited_demo_mode');
    Route::get('/query/{id}/edit','ContactContentController@queryEdit')->name('query.edit');
    if(isModuleActive('MultiVendor')){
        //merchant
        Route::get('/merchant-content','MerchantContentController@index')->name('merchant-content.index');
        Route::post('/merchant-content/update','MerchantContentController@update')->name('merchant-content.update')->middleware('prohibited_demo_mode');
    }
    //benifits
    Route::post('/benefit','BenifitController@store')->name('benefit.store')->middleware('prohibited_demo_mode');
    Route::post('/benefit/update','BenifitController@update')->name('benefit.update')->middleware('prohibited_demo_mode');
    Route::post('/benefit/delete','BenifitController@destroy')->name('benefit.delete')->middleware('prohibited_demo_mode');
    //working process
    Route::post('/how-it-work','WorkingProcessController@store')->name('how-it-work.store')->middleware('prohibited_demo_mode');
    Route::post('/how-it-work/update','WorkingProcessController@update')->name('working-process.update')->middleware('prohibited_demo_mode');
    Route::post('/how-it-work/delete','WorkingProcessController@destroy')->name('working-process.delete')->middleware('prohibited_demo_mode');
    //faq
    Route::post('/faq','FaqController@store')->name('faq.store')->middleware('prohibited_demo_mode');
    Route::post('/faq/update','FaqController@update')->name('faq.update')->middleware('prohibited_demo_mode');
    Route::post('/faq/delete','FaqController@destroy')->name('faq.delete')->middleware('prohibited_demo_mode');
    //dynamic page creator
    Route::resource('/dynamic-page', 'DynamicPageController')->except(['destroy','update']);
    Route::patch('/dynamic-page/{id}','DynamicPageController@update')->name('dynamic-page.update')->middleware('prohibited_demo_mode');
    Route::post('/dynamic-page/store','DynamicPageController@store')->name('dynamic-page.store')->middleware('prohibited_demo_mode');
    Route::post('/dynamic-page/delete','DynamicPageController@destroy')->name('dynamic-page.delete')->middleware('prohibited_demo_mode');
    Route::post('/dynamic-page/status-update','DynamicPageController@status')->name('dynamic-page.status')->middleware('prohibited_demo_mode');
    //homepage manage
    Route::get('/homepage','WidgetController@index')->name('widget.index');
    Route::post('/homepage/getsection-form','WidgetController@getsectionForm')->name('homepage.getsection-form');
    Route::post('/homepage/update','WidgetController@update')->name('homepage.update')->middleware('prohibited_demo_mode');
    Route::get('/title-setting','FrontendCMSController@title_index')->name('title_index');
    Route::post('/title-setting-update','FrontendCMSController@title_update')->name('title_settings.update')->middleware('prohibited_demo_mode');
    //Login Page
    Route::get('/login-page','FrontendCMSController@loginPage')->name('login_page');
    Route::post('/login-page/update','FrontendCMSController@loginPageUpdate')->name('login_page.update')->middleware('prohibited_demo_mode');
    Route::get('/login_page_tab/{id}', 'FrontendCMSController@loginPageTab')->name('login_page.tab');
        //SocialLink
    Route::get('/socialLink','SocialLinkController@social_Link')->name('socialLink');
    Route::post('/socialLink/update','SocialLinkController@socialLink_update')->name('socialLink.update')->middleware('prohibited_demo_mode');
});
Route::middleware(['admin','auth'])->prefix('admin')->as('admin.')->group(function(){
    //pricing
    Route::resource('/pricing', 'PricingController')->except('destroy, update');
    Route::post('/pricing/delete','PricingController@destroy')->name('pricing.delete')->middleware('prohibited_demo_mode');
    Route::post('/pricing/update','PricingController@update')->name('pricing.update')->middleware('prohibited_demo_mode');
    Route::post('/pricing/status-update','PricingController@status')->name('pricing.status')->middleware('prohibited_demo_mode');
    Route::get('/pricings/list-for-seller','PricingController@get_pricing')->name('pricing.get_pricing_url');
        //social link
    Route::post('setting/social-link/store', 'SocialLinkController@socialLinkStore')->name('setting.social-link.store')->middleware('prohibited_demo_mode');
    Route::post('setting/social-link/update', 'SocialLinkController@socialLinkUpdate')->name('setting.social-link.update')->middleware('prohibited_demo_mode');
    Route::post('setting/social-link/delete', 'SocialLinkController@socialLinkDelete')->name('setting.social-link.delete')->middleware('prohibited_demo_mode');
});

Modules/FrontendCMS/Http/Controllers/SocialLinkController.php
<?php

namespace Modules\FrontendCMS\Http\Controllers;

use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Shipping\Repositories\ShippingRepository;
use Illuminate\Support\Facades\Auth;
use Exception;
use Illuminate\Support\Facades\Session;
use Modules\UserActivityLog\Traits\LogActivity;
use Modules\FrontendCMS\Repositories\SocialLinkResitory;

class SocialLinkController extends Controller
{
    protected $seller;

    public function __construct(SocialLinkResitory $seller)
    {
        $this->middleware('maintenance_mode');
        $this->seller = $seller;
    }

    public function social_Link()
    {
        $id = getParentSellerId();
        if(isset($id)){
            $data['socialLinks'] = $this->seller->getSocialLink($id);
            return view('frontendcms::social_link.index',$data);
        }
    }

    public function socialLinkStore(Request $request){

        $request->validate([
            'url' => 'required|max:255',
            'icon' => 'required|max:255',
            'status' => 'required|max:255'
        ]);
        $this->seller->SaveSocilaLink($request->except('_token'));
        LogActivity::successLog('Social link store successful.');
        return $this->loadSocialList();

    }
    public function socialLinkUpdate(Request $request){
        $request->validate([
            'url' => 'required|max:255',
            'icon' => 'required|max:255',
            'status' => 'required|max:255'
        ]);
        $this->seller->UpdateSocilaLink($request->except('_token'),$request->id);
        LogActivity::successLog('Social link update successful.');
        return $this->loadSocialList();
    }
    public function socialLinkDelete(Request $request){
        try {
            $this->seller->linkById($request->id);
            LogActivity::successLog('Social link delete successful.');
        } catch (Exception $e) {
            LogActivity::errorLog($e->getMessage());
            return response()->json([
                'status'    =>  false,
                'message'   =>  $e->getMessage()
            ]);
        }

        return $this->loadSocialList();
    }

    private function loadSocialList()
    {
        try {
            $id  =Auth::user()->id;
            $socialLinks = $this->seller->getSocialLink($id);

            return response()->json([
                'TableData' =>  (string)view('frontendcms::social_link.components.social_link', compact('socialLinks'))
            ],200);

        } catch (\Exception $e) {
            LogActivity::errorLog($e->getMessage());
            Toastr::error(__('common.operation_failed'));
            return response()->json([
                'error' => $e->getMessage()
            ],503);
        }
    }


}

Modules/FrontendCMS/Resources/views/social_link/components/_scripts.blade.php
@push('scripts')

<script src="{{asset(asset_path('backend/vendors/js/icon-picker.js'))}}">
</script>

<script type="text/javascript">
    (function($){
        "use strict";
        $(document).ready(function() {
            $(document).on('mouseover', 'body', function(){
                $('#icon').iconpicker({
                    animation:true
                });
                $('#iconEdit').iconpicker({
                    animation:true
                });

            });

            $(document).on('submit', '#socialLinkCreate', function(event) {
                event.preventDefault();
                $("#social_add_btn").prop('disabled', true);
                $('#social_add_btn').text('{{ __('submitting') }}');
                let formElement = $(this).serializeArray()
                let formData = new FormData();
                formElement.forEach(element => {
                    formData.append(element.name, element.value);
                });
                formData.append('_token', "{{ csrf_token() }}");

                $.ajax({
                    url: "{{ route('admin.setting.social-link.store') }}",
                    type: "POST",
                    cache: false,
                    contentType: false,
                    processData: false,
                    data: formData,
                    success: function(response) {

                        toastr.success("{{__('common.added_successfully')}}","{{__('common.success')}}")
                        $('#social_add').modal('hide');
                        $("#social_add_btn").prop('disabled', false);
                        $('#social_add_btn').text('{{ __('common.save') }}');
                        $('#socialLinkCreate')[0].reset();

                        location.reload();
                    },
                    error: function(response) {
                        $('#social_add_btn').text('{{ __('common.save') }}');
                        if(response.responseJSON.error){
                        toastr.error(response.responseJSON.error ,"{{__('common.error')}}");
                        $('#pre-loader').addClass('d-none');
                        return false;
                    }
                        toastr.error("{{__('common.error_message')}}")
                        showSocialValidationErrors('#socialLinkCreate', response.responseJSON.errors);
                        $("#social_add_btn").prop('disabled', false);
                    }
                });
            });
            $(document).on('submit', '#socialLinkEdit', function(event){
                event.preventDefault();
                $("#social_edit_btn").prop('disabled', true);
                $('#social_edit_btn').text('{{ __('common.updating') }}');
                let formElement = $(this).serializeArray()
                let formData = new FormData();
                formElement.forEach(element => {
                    formData.append(element.name, element.value);
                });
                formData.append('_token', "{{ csrf_token() }}");
                $.ajax({
                url: "{{ route('admin.setting.social-link.update') }}",
                type: "POST",
                cache: false,
                contentType: false,
                processData: false,
                data: formData,
                success: function(response) {
                    $('#social_edit').modal('hide');
                    toastr.success("{{__('common.updated_successfully')}}","{{__('common.success')}}")
                    $("#social_edit_btn").prop('disabled', false);
                    $('#social_edit_btn').text('{{ __('common.update') }}');

                    location.reload();

                },
                error: function(response) {
                    $('#social_edit_btn').text('{{ __('common.update') }}');
                    if(response.responseJSON.error){
                        toastr.error(response.responseJSON.error ,"{{__('common.error')}}");
                        $('#pre-loader').addClass('d-none');
                        return false;
                    }
                    showSocialValidationErrors('#socialLinkEdit', response.responseJSON
                        .errors);
                    $("#social_edit_btn").prop('disabled', false);
                }
                });

            });

            $(document).on('submit','#item_delete_form', function(event) {
                event.preventDefault();

                $("#dataDeleteBtn").prop('disabled', true);
                $('#dataDeleteBtn').val('{{ __('common.deleting') }}');
                var formData = new FormData();
                formData.append('_token', "{{ csrf_token() }}");
                formData.append('id', $('#delete_item_id').val());
                let id = $('#delete_item_id').val();
                $.ajax({
                    url: "{{ route('admin.setting.social-link.delete') }}",
                    type: "POST",
                    cache: false,
                    contentType: false,
                    processData: false,
                    data: formData,
                    success: function(response) {
                        toastr.success("{{__('common.deleted_successfully')}}","{{__('common.success')}}")
                        $('#deleteItemModal').modal('hide');
                        $("#dataDeleteBtn").prop('disabled', false);
                        $('#dataDeleteBtn').val('{{ __('common.delete') }}');
                        location.reload();
                    },
                    error: function(response) {
                        $('#dataDeleteBtn').val('{{ __('common.delete') }}');
                        if(response.responseJSON.error){
                        toastr.error(response.responseJSON.error ,"{{__('common.error')}}");
                        $('#pre-loader').addClass('d-none');
                        return false;
                    }
                        toastr.error("{{__('common.error_message')}}","{{__('common.error')}}");
                        $("#dataDeleteBtn").prop('disabled', false);
                    }
                });
            });

            function resetValidationError(){
                $('#error_method_name').text('');
                $('#error_phone').text('');
                $('#error_cost').text('');
                $('#error_shipment_time').text('');
                $('#error_thumbnail_logo').text('');
            }

            function showValidationErrors(formType, errors){
                $(formType +' #error_method_name').text(errors.method_name);
                $(formType +' #error_phone').text(errors.phone);
                $(formType +' #error_cost').text(errors.cost);
                $(formType +' #error_shipment_time').text(errors.shipment_time);
                $(formType +' #error_thumbnail_logo').text(errors.method_logo);
            }



            $(document).on('click', '.edit_link', function(event){
                event.preventDefault();
                let item = $(this).data('value');
                socialEdit(item);
            });

            $(document).on('click', '.delete_link', function(event){
                let id = $(this).data('id');
                $('#delete_item_id').val(id);
                $('#deleteItemModal').modal('show');
            });

            $(document).on('click', '#dataDeleteBtn', function(event){
                setTimeout(function(){
                    location.reload();
                }, 2000)
            });

            $(document).on('click', '#add_new_shipping', function(event){
                event.preventDefault();
                $('#social_add').modal('show');
            });

            function socialEdit(item){
                $('#social_edit').modal('show');
                $('#socialLinkEdit #iconEdit').val(item.icon);
                $('#socialLinkEdit #urlEdit').val(item.url);
                $('#socialLinkEdit #id').val(item.id);
                if (item.status == 1) {
                    $('#socialLinkEdit #status_activeEdit').prop("checked", true);
                    $('#socialLinkEdit #status_inactiveEdit').prop("checked", false);
                } else {
                    $('#socialLinkEdit #status_activeEdit').prop("checked", false);
                    $('#socialLinkEdit #status_inactiveEdit').prop("checked", true);
                }
            }

            function resetAfterChange(tableData) {
                $('#socialListDiv').empty();
                $('#socialListDiv').html(tableData);
                CRMTableTwoReactive();
            }


            function showSocialValidationErrors(formType, errors){
                $(formType + ' #error_url').text(errors.url);
                $(formType + ' #error_icon').text(errors.icon);
                $(formType + ' #error_status').text(errors.status);
            }
        });

    })(jQuery);

</script>
@endpush