Modules/FrontendCMS/Routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::middleware(['admin','auth'])->prefix('frontendcms')->as('frontendcms.')->group(function() {
    Route::get('/', 'FrontendCMSController@index');
    //feature
    Route::resource('features', 'FeatureController');
    Route::post('/features/store','FeatureController@store')->name('features.store')->middleware('prohibited_demo_mode');
    Route::get('/features/edit/{id}','FeatureController@edit')->name('features.edit');
    Route::post('/features/update/','FeatureController@update')->name('features.update')->middleware('prohibited_demo_mode');
    Route::post('/features/delete','FeatureController@delete')->name('features.delete')->middleware('prohibited_demo_mode');
    //subscribe content
    Route::get('/subscribe-content', 'SubcribeContentController@index')->name('subscribe-content.index');
    Route::post('/subscribe-content/update', 'SubcribeContentController@update')->name('subscribe-content.update')->middleware('prohibited_demo_mode');
    //popup content
    Route::get('/popup-content', 'SubcribeContentController@popup_index')->name('popup-content.index');
    Route::post('/popup-content/update', 'SubcribeContentController@popup_update')->name('popup-content.update')->middleware('prohibited_demo_mode');
    // promotion bar
    Route::get('/promotion-bar','PromotionbarController@index')->name('promotionbar.index');
    Route::post('/promotion-bar/update', 'PromotionbarController@update')->name('promotionbar.update')->middleware('prohibited_demo_mode');
    Route::get('/promotion-bar/remove-image','PromotionbarController@removeImage')->name('promotionbar.removeImage');
    // ads bar
    Route::get('/ads-bar','PromotionbarController@ads_index')->name('ads_bar.index');
    Route::post('/ads-bar/update', 'PromotionbarController@ads_update')->name('ads_bar.update')->middleware('prohibited_demo_mode');
    // random ads
    //about us
    Route::get('/about-us', 'AboutUsController@index')->name('about-us.index');
    Route::post('/about-us/update/{id}', 'AboutUsController@update')->name('about-us.update')->middleware('prohibited_demo_mode');
    //return & exchange
    Route::get('/return-exchange', 'ReturnExchangeController@index')->name('return-exchange.index');
    Route::post('/return-exchange/update', 'ReturnExchangeController@update')->name('return-exchange.update')->middleware('prohibited_demo_mode');
    //contact content
    Route::get('/contact-content', 'ContactContentController@index')->name('contact-content.index');
    Route::post('/contact-content/update', 'ContactContentController@update')->name('contact-content.update')->middleware('prohibited_demo_mode');
    //inquery
    Route::get('/query/create', 'ContactContentController@queryCreate')->name('query.create');
    Route::post('/query/store', 'ContactContentController@queryStore')->name('query.store')->middleware('prohibited_demo_mode');
    Route::post('/query/update','ContactContentController@queryUpdate')->name('query.update')->middleware('prohibited_demo_mode');
    Route::post('/query/delete','ContactContentController@destroy')->name('query.delete')->middleware('prohibited_demo_mode');
    Route::post('/query/status-update','ContactContentController@status')->name('query.status')->middleware('prohibited_demo_mode');
    Route::get('/query/{id}/edit','ContactContentController@queryEdit')->name('query.edit');
    if(isModuleActive('MultiVendor')){
        //merchant
        Route::get('/merchant-content','MerchantContentController@index')->name('merchant-content.index');
        Route::post('/merchant-content/update','MerchantContentController@update')->name('merchant-content.update')->middleware('prohibited_demo_mode');
    }
    //benifits
    Route::post('/benefit','BenifitController@store')->name('benefit.store')->middleware('prohibited_demo_mode');
    Route::post('/benefit/update','BenifitController@update')->name('benefit.update')->middleware('prohibited_demo_mode');
    Route::post('/benefit/delete','BenifitController@destroy')->name('benefit.delete')->middleware('prohibited_demo_mode');
    //working process
    Route::post('/how-it-work','WorkingProcessController@store')->name('how-it-work.store')->middleware('prohibited_demo_mode');
    Route::post('/how-it-work/update','WorkingProcessController@update')->name('working-process.update')->middleware('prohibited_demo_mode');
    Route::post('/how-it-work/delete','WorkingProcessController@destroy')->name('working-process.delete')->middleware('prohibited_demo_mode');
    //faq
    Route::post('/faq','FaqController@store')->name('faq.store')->middleware('prohibited_demo_mode');
    Route::post('/faq/update','FaqController@update')->name('faq.update')->middleware('prohibited_demo_mode');
    Route::post('/faq/delete','FaqController@destroy')->name('faq.delete')->middleware('prohibited_demo_mode');
    //dynamic page creator
    Route::resource('/dynamic-page', 'DynamicPageController')->except(['destroy','update']);
    Route::patch('/dynamic-page/{id}','DynamicPageController@update')->name('dynamic-page.update')->middleware('prohibited_demo_mode');
    Route::post('/dynamic-page/store','DynamicPageController@store')->name('dynamic-page.store')->middleware('prohibited_demo_mode');
    Route::post('/dynamic-page/delete','DynamicPageController@destroy')->name('dynamic-page.delete')->middleware('prohibited_demo_mode');
    Route::post('/dynamic-page/status-update','DynamicPageController@status')->name('dynamic-page.status')->middleware('prohibited_demo_mode');
    //homepage manage
    Route::get('/homepage','WidgetController@index')->name('widget.index');
    Route::post('/homepage/getsection-form','WidgetController@getsectionForm')->name('homepage.getsection-form');
    Route::post('/homepage/update','WidgetController@update')->name('homepage.update')->middleware('prohibited_demo_mode');
    Route::get('/title-setting','FrontendCMSController@title_index')->name('title_index');
    Route::post('/title-setting-update','FrontendCMSController@title_update')->name('title_settings.update')->middleware('prohibited_demo_mode');
    //Login Page
    Route::get('/login-page','FrontendCMSController@loginPage')->name('login_page');
    Route::post('/login-page/update','FrontendCMSController@loginPageUpdate')->name('login_page.update')->middleware('prohibited_demo_mode');
    Route::get('/login_page_tab/{id}', 'FrontendCMSController@loginPageTab')->name('login_page.tab');
        //SocialLink
    Route::get('/socialLink','SocialLinkController@social_Link')->name('socialLink');
    Route::post('/socialLink/update','SocialLinkController@socialLink_update')->name('socialLink.update')->middleware('prohibited_demo_mode');
});
Route::middleware(['admin','auth'])->prefix('admin')->as('admin.')->group(function(){
    //pricing
    Route::resource('/pricing', 'PricingController')->except('destroy, update');
    Route::post('/pricing/delete','PricingController@destroy')->name('pricing.delete')->middleware('prohibited_demo_mode');
    Route::post('/pricing/update','PricingController@update')->name('pricing.update')->middleware('prohibited_demo_mode');
    Route::post('/pricing/status-update','PricingController@status')->name('pricing.status')->middleware('prohibited_demo_mode');
    Route::get('/pricings/list-for-seller','PricingController@get_pricing')->name('pricing.get_pricing_url');
        //social link
    Route::post('setting/social-link/store', 'SocialLinkController@socialLinkStore')->name('setting.social-link.store')->middleware('prohibited_demo_mode');
    Route::post('setting/social-link/update', 'SocialLinkController@socialLinkUpdate')->name('setting.social-link.update')->middleware('prohibited_demo_mode');
    Route::post('setting/social-link/delete', 'SocialLinkController@socialLinkDelete')->name('setting.social-link.delete')->middleware('prohibited_demo_mode');
});

Modules/FrontendCMS/Resources/views/merchant/benefit/create.blade.php
<div id="add_item_modal">
    <div class="modal fade" id="item_add">
        <div class="modal-dialog modal_800px modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">
                        {{ __('common.add_new') }}
                    </h4>
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="ti-close "></i>
                    </button>
                </div>
                <div class="modal-body item_create_form">
                    @include('frontendcms::merchant.benefit.form',['form_id' => 'item_create_form','benefit_modal_tab_id' => 'bmcelement','btn_id' => 'create_benefit_btn', 'button_level_name' => __('common.save') ])
                </div>
            </div>
        </div>
    </div>
</div>

Modules/FrontendCMS/Resources/views/merchant/benefit/edit.blade.php
<div id="edit_item_modal">
    <div class="modal fade" id="item_edit">
        <div class="modal-dialog modal_800px modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">
                        {{ __('frontendCms.update_benefit') }}
                    </h4>
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="ti-close "></i>
                    </button>
                </div>
                <div class="modal-body item_edit_form">
                    <input type="hidden" name="id" id="item_id">
                    @include('frontendcms::merchant.benefit.form',['form_id' => 'item_edit_form', 'benefit_modal_tab_id' => 'ebmelement', 'btn_id' => 'edit_benefit_btn', 'button_level_name' => __('common.update') ])
                </div>
            </div>
        </div>
    </div>
</div>

Modules/FrontendCMS/Resources/views/merchant/benefit/form.blade.php
<form id="{{ $form_id }}" method="POST" action="{{route('frontendcms.benefit.store')}}" enctype="multipart/form-data">
    @csrf
    <div class="row">
        @if(isModuleActive('FrontendMultiLang'))
            <div class="col-lg-12">
                <ul class="nav nav-tabs justify-content-start mt-sm-md-20 mb-30 grid_gap_5" role="tablist">
                    @foreach ($LanguageList as $key => $language)
                        <li class="nav-item lang_code" data-id="{{$language->code}}">
                            <a class="nav-link anchore_color @if (auth()->user()->lang_code == $language->code) active @endif" href="#{{$benefit_modal_tab_id}}{{$language->code}}" role="tab" data-toggle="tab" aria-selected="@if (auth()->user()->lang_code == $language->code) true @else false @endif">{{ $language->native }} </a>
                        </li>
                    @endforeach
                </ul>
                <div class="tab-content">
                    @foreach ($LanguageList as $key => $language)
                        <div role="tabpanel" class="tab-pane fade @if (auth()->user()->lang_code == $language->code) show active @endif" id="{{$benefit_modal_tab_id}}{{$language->code}}">
                            <div class="row">                                
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <div class="primary_input mb-25">
                                        <label class="primary_input_label" for="">{{ __('common.title') }} <span class="text-danger">*</span></label></label>
                                        <input name="title[{{$language->code}}]" class="primary_input_field title" id="title{{$language->code}}" placeholder="{{ __('common.title') }}" type="text" value="{{old('title.'.$language->code)}}">
                                    </div>
                                    <span class="text-danger"  id="create_error_title_{{$language->code}}"></span>
                                </div>
                                <div class="col-xl-12">
                                    <div class="primary_input mb-35">
                                        <label class="primary_input_label" for="">{{ __('common.details') }} <span class="text-danger">*</span></label>
                                        <textarea name="description[{{$language->code}}]" placeholder="{{ __('common.description') }}" class="benefit_description" id="description{{$language->code}}">{{old('description.'.$language->code)}}</textarea>
                                    </div>
                                    <span class="text-danger" id="create_error_description_{{$language->code}}"></span>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        @else
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="primary_input mb-25">
                    <label class="primary_input_label" for="">{{ __('common.title') }} <span class="text-danger">*</span></label></label>
                    <input name="title" class="primary_input_field title" id="title" placeholder="{{ __('common.title') }}" type="text">
                </div>
                <span class="text-danger"  id="create_error_title"></span>
            </div>
            <div class="col-xl-12">
                <div class="primary_input mb-35">
                    <label class="primary_input_label" for="">{{ __('common.details') }} <span class="text-danger">*</span></label>
                    <textarea name="description" placeholder="{{ __('common.description') }}" class="benefit_description" id="description"></textarea>
                </div>
                <span class="text-danger" id="create_error_description"></span>
            </div>
        @endif
        <div class="col-xl-12" id="cerate_img_div_for_benefit">
            <div class="primary_input mb-35">
                <label class="primary_input_label" for="">{{__('common.image')}} <span class="text-danger">*</span><small class="ml-1">({{getNumberTranslate(80)}}x{{getNumberTranslate(60)}})</small> </label>
                <div class="primary_file_uploader">
                    <input class="primary-input" type="text" id="benifit_{{$form_id}}" placeholder="{{__('common.browse_image_file')}}" readonly="">
                    <button class="" type="button">
                    <label class="primary-btn small fix-gr-bg" for="{{$form_id}}_image"><span class="ripple rippleEffect benefit_img_custom_style"></span>{{__('common.browse')}}</label>
                        <input name="image" type="file" class="d-none benefit_image" data-show_name_id="#benifit_{{$form_id}}" data-img_id="#BenefitImgshow_{{$form_id}}" id="{{$form_id}}_image">
                    </button>
                    <span class="text-danger" id="create_error_image"></span><br>
                    <img id="BenefitImgshow_{{$form_id}}" class="benefit_img_show" src="{{showImage('backend/img/default.png')}}" alt="">
                </div>
            </div>
        </div>
        <div class="col-xl-12">
            <div class="primary_input">
                <label class="primary_input_label" for="">{{ __('common.status') }} <span class="text-danger">*</span></label></label>
                <ul id="theme_nav" class="permission_list sms_list ">
                    <li>
                        <label data-id="bg_option" class="primary_checkbox d-flex mr-12">
                            <input name="status" id="status_active" value="1" checked="true" class="active" type="radio">
                            <span class="checkmark"></span>
                        </label>
                        <p>{{ __('common.active') }}</p>
                    </li>
                    <li>
                        <label data-id="color_option" class="primary_checkbox d-flex mr-12">
                            <input name="status" value="0" id="status_inactive"  class="de_active" type="radio">
                            <span class="checkmark"></span>
                        </label>
                        <p>{{ __('common.inactive') }}</p>
                    </li>
                </ul>
            </div>
            <span class="text-danger" id="create_error_status"></span>
        </div>
        <div class="col-lg-12 text-center">
            <div class="d-flex justify-content-center pt_20">
            <button id="{{ $btn_id }}" type="submit" class="primary-btn semi_large2 fix-gr-bg"><i class="ti-check"></i>{{ $button_level_name }} </button>
            </div>
        </div>
    </div>
</form>

Modules/FrontendCMS/Resources/views/merchant/benefit/list.blade.php
<div class="table-responsive">
    <table id="default_table" class="display school-table no-footer dtr-inline dataTable benefit_table"
        cellspacing="0" width="100%" role="grid" aria-describedby="default_table_info">
        @if (count($BenefitList) < 4 )
        <a href="" class="primary-btn small tr-bg icon-only mr-10 modalLink pull-right add_benefit_modal" title="Create Class Routine">
            <span class="ti-plus" id="add benefit"></span>
        </a>
        @endif
        <thead>
            <tr class="text-center" role="row">
                <th class="" tabindex="0" aria-controls="default_table" class="width-60" aria-label="" aria-sort="ascending">{{__('common.sl')}}</th>
                <th class="" tabindex="0" aria-controls="default_table" rowspan="1" colspan="1" class="width-83" aria-label="">{{__('common.title')}}</th>
                <th class="" tabindex="0" aria-controls="default_table" rowspan="1" colspan="1" class="width-83" aria-label="">{{__('common.status')}}</th>
                <th class="" tabindex="0" aria-controls="default_table" rowspan="1" colspan="1" class="width-83" aria-label="">{{__('common.action')}}</th>    
            </tr>
        </thead>
        <tbody>
            @foreach ($BenefitList as $key => $item)
            <tr class="text-center" id="benefit-td">
                <td>{{ getNumberTranslate($key + 1) }}</td>
                <td>{{ $item->title }}</td>
                <td>{{ $item->status?'Active':'Inactive' }}</td>
                <td> <p><i data-value="{{$item}}" class="fas fa-edit cus-poi edit_benefit"></i> <i data-id="{{$item->id}}" class="fas fa-trash-alt cus-poi ml-10 delete_benefit"></i>
                </p></td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>